<?php

?>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/Montserrat.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/pikaday/1.6.1/css/pikaday.min.css">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/default.min.css"/>
    <link rel="stylesheet" href="assets/css/Navbar-Centered-Links.css">
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css"/>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.11.1/baguetteBox.min.css">
    <link href="assets/css/bootstrap.min.css" rel="stylesheet">
    <link href="assets/css/custom.css" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/untitled.css">
    <link rel="stylesheet" href="assets/css/styles.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> 
    <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css?h=21f14b60305aa9b0449170550a54b7e5">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css">
    <link rel="stylesheet" href="assets/css/Kaushan%20Script.css">
     <!-- Favicon -->
    <link rel="icon" href="uploads/favicon.ico"/>
    <title>Privacy Policy | Terms of Use</title>
</head>
<body>
<nav class="navbar navbar-expand-md fixed-top navbar-shrink py-3" id="mainNav" style="background-color:rgb(255,128,64); box-shadow: 0px 0px 18px var(--bs-gray); height: 80px;">
            <div class="container ml-2">
                <a class="navbar-brand" href="index.php" style="color: white;font-size: 28px;">
                    <span><img src="uploads/logoT.png" usemap=#workmap style="width: 50px;">&nbsp;</span>
                        <map name="workmap">
                            <area shape="circle" coords="100,100,300,300" alt="logo" href="index.php">
                        </map>I - Eat</a>
                <nav class="navbar navbar-expand">
                    <div class="container-fluid">
                        <span class="bs-icon-md d-flex justify-content-center align-items-center me-2 bs-icon" style="background: transparent;">
                        <a href="index.php"><i class="fa fa-home" style="float:right; color:white;"></i></a>
                        </span></div>
                </nav>
            </div>
        </nav>
        <div class="container" id="policy_terms">
            <div class="row justify-content-center">
                <div class="col-md-9">
                    <h5 class="mb-2">Definitions and Key Terms</h5>
                    <p class="terms_content">
                        To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, are strictly defined as: <br>
                        • <span class="fw-bold">Cookie:</span>&nbsp; Small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.<br>
                        • <span class="fw-bold">Company:</span>&nbsp; When this policy mentions "Company," it refers to I-Eat, I-Eat that is responsible for your information under this Privacy Policy.<br>
                        • <span class="fw-bold">Country:</span>&nbsp; Where I-Eat or the owners/founders of I-Eat are based, in this case is the Philippines.<br>
                        • <span class="fw-bold">Customer:</span>&nbsp; Refers to the company, organization or person that signs up to use the l-Eat Service to manage the relationships with your consumers or service users.<br>
                        • <span class="fw-bold">Device:</span>&nbsp; Any internet connected device such as a phone, tablet, computer or any other device that can be used to visit l-Eat and use the services.<br>
                        • <span class="fw-bold">IP address:</span>&nbsp; Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.<br>
                        • <span class="fw-bold">Personnel:</span>&nbsp; Refers to those individuals who are employed by I-Eat or are under contract to perform a service on behalf of one of the parties.<br>
                        • <span class="fw-bold">Personal Data:</span>&nbsp; Any information that directly, indirectly, or in connection. with other information - including a personal identification number - allows for the identification or identifiability of a natural person.<br>
                        • <span class="fw-bold">Service:</span>&nbsp; Refers to the service provided by l-Eat as described in the relative terms (if available) and on this platform.<br>
                        • <span class="fw-bold">Third-party service:</span>&nbsp; Refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.<br>
                        • <span class="fw-bold">Website:</span>&nbsp; I-Eat's site, which can be accessed via this URL:<i class="fw-bold"> https://ieat.store.</i><br>
                        • <span class="fw-bold">You:</span>&nbsp; A person or entity that is registered with I-Eat to use the service.<br>
                    </p>
                </div>
            </div>
        </div>
</body>
